# .bashrc
 PS1="[\w]"

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

source ~/.git-prompt.sh
export PS1='\[\033[01;32m\]\u\[\033[0;34m\] [\@] \[\033[00;34m\] \w \[\033[01;34m\]$(__git_ps1)\[\033[01;36m\] \$\[\033[00m\] '

# User specific aliases and functions
alias vi='vim'
alias v='vim'
alias ne='emacs -nw'
alias e='ne'
alias ls='ls --color'
alias us='setxkbmap us'
alias fr='setxkbmap fr'
alias us_i='setxkbmap us -variant alt-intl'
alias 3w='cd /var/www/html'
alias b_scan='hcitool scan'
alias xrandr_auto='xrandr --auto'
alias xrandr_right='xrandr --output eDP1 --left-of DP3'
alias xrandr_left='xrandr --output eDP1 --right-of DP3'
alias ngl='./node_modules/.bin/ng'
alias nvset='optirun -b none nvidia-settings -c :8'
alias bb='cat /proc/acpi/bbswitch'
alias bbs='optirun --status'
alias optisteam='LD_PRELOAD= __GL_THREADED_OPTIMIZATIONS=1 %command% -nostartupmovies;optirun steam'

# REMINDER
alias show_nginx_folder='/usr/share/nginx/html'

export TERM='xterm-256color'

export PATH="$PATH:$HOME/.npm/bin"
export PATH=~/.local/bin:$PATH
export PATH="$HOME/.cargo/bin:$PATH"


# NVM
source /usr/share/nvm/init-nvm.sh
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"

# tabtab source for serverless package
# uninstall by removing these lines or running `tabtab uninstall serverless`
[ -f /home/dlacreme/work/souqalmal/car-insurance-app/node_modules/tabtab/.completions/serverless.bash ] && . /home/dlacreme/work/souqalmal/car-insurance-app/node_modules/tabtab/.completions/serverless.bash
# tabtab source for sls package
# uninstall by removing these lines or running `tabtab uninstall sls`
[ -f /home/dlacreme/work/souqalmal/car-insurance-app/node_modules/tabtab/.completions/sls.bash ] && . /home/dlacreme/work/souqalmal/car-insurance-app/node_modules/tabtab/.completions/sls.bash
# tabtab source for slss package
# uninstall by removing these lines or running `tabtab uninstall slss`
[ -f /home/dlacreme/work/souqalmal/car-insurance-app/node_modules/tabtab/.completions/slss.bash ] && . /home/dlacreme/work/souqalmal/car-insurance-app/node_modules/tabtab/.completions/slss.bash

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="/home/dlacreme/.sdkman"
[[ -s "/home/dlacreme/.sdkman/bin/sdkman-init.sh" ]] && source "/home/dlacreme/.sdkman/bin/sdkman-init.sh"
